version: "3"
networks:
  iig_sse:
    external: true
volumes:
  bundle:
  postgres:
services:
  db:
    image: postgres:13-alpine
    ports:
      - 5437:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - bundle:/usr/local/bundle
      - .:/usr/src/app:delegated
      - /vendor
      - /tmp
      - /log
      - /.git
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - SECRET_KEY_BASE=d140269c106b6d064cdd670a5aace0bbbb1400de545377a47836dbdab8104f2fdf0ab87e6b7982819d1bcc2ccf6a5f093985a0895970f01f30b0b15378a090e9
    ports:
      - 80:3000
    depends_on:
      - db
    networks:
      - iig_sse
      - default
