INSERT INTO departments(id,name,description,created_at,updated_at) VALUES
(1,'Ban Giám đốc Công ty',null,now(),now()),
(2,'Ban Thư ký - Trợ lý',null,now(),now()),
(3,'Nhân sự',null,now(),now()),
(4,'Văn phòng',null,now(),now()),
(5,'Kế toán',null,now(),now()),
(6,'Kinh doanh',null,now(),now()),
(7,'Học viện IIG',null,now(),now()),
(8,'Dự án 1',null,now(),now()),
(9,'Phòng Phát triển sản phẩm CNTT',null,now(),now()),
(10,'Dự án 2',null,now(),now()),
(11,'Tổ chức thi',null,now(),now()),
(12,'Marketing',null,now(),now()),
(13,'IT',null,now(),now()),
(14,'Ban Giám đốc Chi nhánh HCM',null,now(),now()),
(15,'Dự án HCM',null,now(),now()),
(16,'Hành chính nhân sự HCM',null,now(),now()),
(17,'Kế toán HCM',null,now(),now()),
(18,'Kinh doanh HCM',null,now(),now()),
(19,'Tổ chức thi HCM',null,now(),now()),
(20,'Chi nhánh Đà Nẵng',null,now(),now())
